name: Code Coverage

on:
  pull_request:
    branches:
      - main  
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      # Step 3: Install dependencies in `src`
      # - name: Install dependencies
      #   working-directory: src
      #   run: |
      #     npm install
      #     npm install --save-dev jest jest-junit

      # # Step 4: Run Jest tests with coverage and JUnit report
      # - name: Run Jest tests
      #   working-directory: src
      #   run: |
      #     mkdir -p reports
      #     JEST_JUNIT_OUTPUT="junit.xml" npx jest --coverage --reporters=default --reporters=jest-junit
      - name: Install dependencies
        working-directory: src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test with pytest
        working-directory: src
        run: |
          pytest --cov --junitxml=junit.xml
      # Step 5: Upload coverage to Codecov
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: src/coverage/clover.xml
      #     flags: unittests

      # Step 6: Upload JUnit test results to Codecov
      # - name: Upload test results to Codecov
      #   if: ${{ !cancelled() }}
      #   uses: codecov/test-results-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: src/junit.xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
