name: Code Coverage

on:
  pull_request:
    branches:
      - main  

jobs:
  lint:
    name: Run Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Test  
        working-directory: src
        run: npx jest --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
