name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checko
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key and pe
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$GCP_VM_IP ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDiu3RP40WplGARD7sw2GDmvlV6/XHB3dkx4JHbT+PwB" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}

      # Step 3: Copy application code to the GCP VM
      - name: Transfer application to GCP VM
        run: |
          scp -o StrictHostKeyChecking=no -r ./ aryan@$GCP_VM_IP:/home/aryan/
        env:
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}

      # Step 4: Install dependencies and restart server on the GCP VM
      - name: Deploy application on GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no aryan@$GCP_VM_IP << 'EOF'
          cd /home/aryan/
          npm install
          pm2 stop server || true
          pm2 start server.js --name "node-app"
          EOF
        env:
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
