name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCP VM
        run: |
          scp -o StrictHostKeyChecking=no -r ./ $GCP_VM_USER@$GCP_VM_IP:/home/$GCP_VM_USER/app
          ssh -o StrictHostKeyChecking=no $GCP_VM_USER@$GCP_VM_IP << 'EOF'
          cd /home/$GCP_VM_USER/app
          npm install
          pm2 stop server || true
          pm2 start server.js --name "node-app"
          EOF
        env:
          GCP_VM_IP: 104.155.190.17
          GCP_VM_USER: gcp
