name: UI test
on:
  workflow_run:
    workflows:
      - Deployment
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Script Install
      run: |
        cd uiTestSuite/src/ && npm install
        sudo apt-get update
        sudo apt-get install -y fonts-liberation ca-certificates libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 \ibpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
        sudo apt-get install -y xvfb

    - name: E2E Test
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &
        cd uiTestSuite/src/ && npm run uitest | sed 's/\(✔ UT - .*\)/\033[0;32m\1\033[0m/'
