name: Lint and Test

on:
  pull_request:
    branches:
      - main  
  push:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: cd src && npm install

      - name: Run ESLint Checks 
        working-directory: src
        id: eslint
        run: |
          files=("home.js" "./new-page/editor.js")  
          for file in "${files[@]}"; do
            echo "Running ESLint on $file"
            if npx eslint "$file"; then
              echo -e "\033[32m✔ ESLint Passed for $file\033[0m"
            else
              echo -e "\033[31m✘ ESLint Failed for $file. Please fix errors.\033[0m"
              exit 1  # Fail the workflow if any file fails
            fi
          done
